---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/activity":
    get:
      summary: GET user activity
      tags:
      - User::Activity
      description: User recent activities
      security:
      - Bearer: []
      responses:
        '200':
          description: GET /api/activities
    post:
      summary: POST user activity
      tags:
      - User::Activity
      description: Create new activity
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: POST user activity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activity:
                  type: object
                  properties:
                    id:
                      type: integer
                      default: 2
  "/oauth/token":
    post:
      summary: returns a login credentials
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: fetches a token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: test01@test.com
                password:
                  type: string
                  default: 123456abc@
                grant_type:
                  type: string
                  default: password
                client_id:
                  type: string
                  default: yPomFOwElqDKvSDk82PuKipmo0LScIm4j_5H_zB5_KM
                client_secret:
                  type: string
                  default: MzUuHA6_DnNZme61VY2Zzc3mxqzS53H0iNGuqIcW6aE
  "/api/dashboard":
    get:
      summary: fetches user dashboard data
      tags:
      - User::Dashboard
      description: User Dashboard JSON data
      security:
      - Bearer: []
      responses:
        '200':
          description: GET /api/dashboard
  "/api/export":
    post:
      summary: Export User activity stats
      tags:
      - User::Export
      description: Export User activity to external resource in JSON format
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: POST /api/export
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  default: '2021-09-25'
                to:
                  type: string
                  default: '2021-09-26'
  "/api/goals":
    get:
      summary: GET all current goals
      tags:
      - User::Goals
      description: Goals to display on user profile creation process
      security:
      - Bearer: []
      responses:
        '200':
          description: GET Goals JSON
  "/api/signup":
    post:
      summary: creates user account with app credentials
      tags:
      - User
      description: POST with user and app payload creates a user record
      parameters: []
      responses:
        '200':
          description: creates a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: test@test.com
                    password:
                      type: string
                      default: 123456abc@
                    terms_accepted_at:
                      type: boolean
                    client_id:
                      type: string
                      default: yPomFOwElqDKvSDk82PuKipmo0LScIm4j_5H_zB5_KM
                    client_secret:
                      type: string
                      default: MzUuHA6_DnNZme61VY2Zzc3mxqzS53H0iNGuqIcW6aE
servers:
- url: http://localhost:3000
  description: Local development
  variables:
    defaultHost:
      default: localhost:3000
- url: https://vellbie-server-staging.herokuapp.com
  description: Staging server
components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
