name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost

jobs:
  ruby_dependencies:
    name: Ruby - download and cache dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    needs: ruby_dependencies
    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Setup test database
        run: bundle exec rails db:create db:migrate

      - name: Run RSpec
        run: bundle exec rspec

  rubocop:
    name: Run Rubocop
    runs-on: ubuntu-latest
    needs: ruby_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle

      # - name: Run Rubocop
        # run: bundle exec rubocop
